In [1]:
def compare_lists(list_a, list_b):
  """Compares two lists and returns a list of values that are in list A but not in list B.

  Args:
    list_a: A list of objects.
    list_b: A list of objects.

  Returns:
    A list of values that are in list_a but not in list_b.
  """

  list_difference = []

  for item in list_a:
    if item not in list_b:
      list_difference.append(item)

  return list_difference

In [2]:
import pandas as pd
from myUtils import pickle_load, pickle_dump
pd.set_option('display.max_rows', 50)
pd.set_option('display.max_columns', 30)
pd.set_option('display.max_colwidth', 30)
pd.set_option('display.width', 900)

path_dir = "C:/Users/ping/MyDrive/stocks/yfinance/"
path_data_dump = path_dir + "VSCode_dump/"

# pickle file of past picks
fp_df_picks  = f'df_picks'
# pickle file of NYSE dates missing from df_picks
fp_NYSE_dates_missing_in_df_picks = f'NYSE_dates_missing_in_df_picks'

In [3]:
df_picks = pickle_load(path_data_dump, fp_df_picks)
# drop duplicates
df_picks = df_picks.drop_duplicates(subset=['date_end_df_train', 'max_days_lookbacks', 'days_lookbacks'], keep='last')
# sort, most recent date is first
df_picks = df_picks.sort_values(by=['date_end_df_train', 'max_days_lookbacks', 'days_lookbacks'], ascending=False)
# re-index
df_picks = df_picks.reset_index(drop=True)
# save results
pickle_dump(df_picks, path_data_dump, fp_df_picks)
print(f'df_picks, len({len(df_picks)}):\n{df_picks}')

df_picks, len(280):
    date_end_df_train  max_days_lookbacks     days_lookbacks sym_freq_15 sym_freq_14 sym_freq_13 sym_freq_12      sym_freq_11      sym_freq_10              sym_freq_9       sym_freq_8                     sym_freq_7                     sym_freq_6                     sym_freq_5                     sym_freq_4                     sym_freq_3 sym_freq_2
0          2023-11-08                 120      [30, 60, 120]          []          []          []          []               []               []         ['FTSM', 'SHV']          ['NRG']        ['ANF', 'CBOE', 'GBTC']                ['LRN', 'USAC']                 ['EDU', 'GPS']  ['AGYS', 'DELL', 'TGH', 'YY']  ['BTC-USD', 'CAH', 'CLS', ...         []
1          2023-11-08                 120  [15, 30, 60, 120]          []          []          []          []               []  ['FTSM', 'SHV']  ['GBTC', 'LRN', 'NRG']               []  ['AGYS', 'ANF', 'CBOE', 'T...            ['BTC-USD', 'USAC']                 ['EDU', 'GPS']         ['DELL', 'PLNT', 'YY']  ['BPMC', 'BZH', 'CAH', 'CLS']         []
2          2023-11-07                 120      [30, 60, 120]          []          []          []          []               []               []         ['FTSM', 'SHV']          ['NRG']        ['ANF', 'CBOE', 'GBTC']                       ['USAC']                        ['LRN']           ['EDU', 'GPS', 'YY']  ['AGYS', 'BTC-USD', 'CAH',...         []
3          2023-11-07                 120  [15, 30, 60, 120]          []          []          []          []          ['SHV']         ['FTSM']                ['GBTC']   ['LRN', 'NRG']                ['ANF', 'CBOE']  ['AGYS', 'BTC-USD', 'TGH',...                             []  ['EDU', 'GPS', 'ICPT', 'PL...          ['CAH', 'CLF', 'CLS']         []
4          2023-11-06                 120      [30, 60, 120]          []          []          []          []               []               []         ['FTSM', 'SHV']          ['NRG']                ['ANF', 'CBOE']                       ['USAC']                 ['GPS', 'LRN']                       ['GBTC']  ['AGYS', 'BTC-USD', 'CLS',...         []
..                ...                 ...                ...         ...         ...         ...         ...              ...              ...                     ...              ...                            ...                            ...                            ...                            ...                            ...        ...
275        2023-03-17                 120  [15, 30, 60, 120]          []          []          []          []          ['SHV']               []          ['FTSM', 'GE']               []               ['NVDA', 'SGEN']  ['ANET', 'FCN', 'GBTC', 'T...  ['ACLS', 'FSLR', 'HY', 'LN...         ['AMD', 'ATCO', 'MLR']                       ['AJRD']         []
276        2023-03-16                 120      [30, 60, 120]          []          []          []          []               []               []         ['FTSM', 'SHV']               []                             []        ['LNTH', 'SGEN', 'WST']  ['ACLS', 'AMPH', 'CTLT', '...           ['HY', 'MLR', 'OEC']  ['ANET', 'ATCO', 'ATKR', '...         []
277        2023-03-16                 120  [15, 30, 60, 120]          []          []          []          []               []  ['FTSM', 'SHV']                ['SGEN']               []                        ['MLR']  ['ANET', 'FCN', 'FSLR', 'G...  ['ACLS', 'AMPH', 'CTLT', '...                             []                             []         []
278        2023-03-15                 120      [30, 60, 120]          []          []          []          []               []               []         ['FTSM', 'SHV']               []                             []  ['CTLT', 'ELF', 'SGEN', 'T...  ['ACLS', 'AMPH', 'FCN', 'GE']  ['ATCO', 'HY', 'LNTH', 'ME...  ['ATKR', 'BURL', 'FIZZ', '...         []
279        2023-03-15                 120  [15, 30, 60, 120]          []          []          []          []  ['FTSM', 'SHV']               []                ['SGEN']  ['AMPH', 'FCN']           ['GE', 'HY', 'META']  ['CTLT', 'ELF', 'FIZZ', 'M...       ['ACLS', 'ANET', 'SRPT']               ['ATCO', 'LNTH']                             []         []

[280 rows x 17 columns]

In [4]:
start_date = df_picks.date_end_df_train.min()
end_date = df_picks.date_end_df_train.max()
print(f'df_picks start date: {start_date}')
print(f'df_picks end date: {end_date}')

df_picks start date: 2023-03-15
df_picks end date: 2023-11-08

In [5]:
l_dates_df_picks = df_picks.date_end_df_train.unique().tolist()  # unique dates in df_picks
print(f'l_dates_df_picks, len({len(l_dates_df_picks)}):\n{l_dates_df_picks}')

l_dates_df_picks, len(140):
['2023-11-08', '2023-11-07', '2023-11-06', '2023-11-03', '2023-11-02', '2023-11-01', '2023-10-31', '2023-10-30', '2023-10-27', '2023-10-26', '2023-10-25', '2023-10-24', '2023-10-23', '2023-10-20', '2023-10-19', '2023-10-17', '2023-10-12', '2023-10-06', '2023-10-05', '2023-10-04', '2023-10-02', '2023-09-29', '2023-09-28', '2023-09-25', '2023-09-22', '2023-09-21', '2023-09-20', '2023-09-18', '2023-09-15', '2023-09-14', '2023-09-13', '2023-09-12', '2023-09-11', '2023-09-08', '2023-09-05', '2023-09-01', '2023-08-25', '2023-08-18', '2023-08-17', '2023-08-15', '2023-08-14', '2023-08-11', '2023-08-10', '2023-08-09', '2023-08-08', '2023-08-07', '2023-08-04', '2023-08-03', '2023-08-02', '2023-08-01', '2023-07-27', '2023-07-26', '2023-07-25', '2023-07-21', '2023-07-20', '2023-07-18', '2023-07-14', '2023-07-13', '2023-07-12', '2023-07-11', '2023-07-10', '2023-07-07', '2023-07-06', '2023-07-05', '2023-07-03', '2023-06-30', '2023-06-29', '2023-06-28', '2023-06-27', '2023-06-26', '2023-06-23', '2023-06-22', '2023-06-21', '2023-06-20', '2023-06-16', '2023-06-15', '2023-06-14', '2023-06-13', '2023-06-12', '2023-06-09', '2023-06-08', '2023-06-07', '2023-06-06', '2023-06-05', '2023-06-02', '2023-06-01', '2023-05-31', '2023-05-30', '2023-05-26', '2023-05-25', '2023-05-24', '2023-05-23', '2023-05-22', '2023-05-19', '2023-05-18', '2023-05-17', '2023-05-16', '2023-05-15', '2023-05-12', '2023-05-11', '2023-05-10', '2023-05-09', '2023-05-08', '2023-05-05', '2023-05-04', '2023-05-03', '2023-05-02', '2023-05-01', '2023-04-28', '2023-04-27', '2023-04-26', '2023-04-25', '2023-04-24', '2023-04-21', '2023-04-20', '2023-04-19', '2023-04-18', '2023-04-17', '2023-04-14', '2023-04-13', '2023-04-12', '2023-04-11', '2023-04-10', '2023-04-06', '2023-04-05', '2023-04-04', '2023-04-03', '2023-03-31', '2023-03-30', '2023-03-29', '2023-03-28', '2023-03-27', '2023-03-24', '2023-03-23', '2023-03-22', '2023-03-21', '2023-03-20', '2023-03-17', '2023-03-16', '2023-03-15']

In [6]:
import pandas_market_calendars as mcal
nyse = mcal.get_calendar('NYSE')
# NYSE dates from df_picks start date to end date
dates_NYSE = nyse.valid_days(start_date=start_date, end_date=end_date).strftime('%Y-%m-%d')
# print(f'len(dates_NYSE): {len(dates_NYSE)}')
dates_NYSE_reversed_sorted = dates_NYSE.sort_values(ascending=False)
print('NYSE dates from df_picks start date to end date')
print(f'dates_NYSE_reversed_sorted, len({len(dates_NYSE)}):\n{dates_NYSE_reversed_sorted}')

NYSE dates from df_picks start date to end date
dates_NYSE_reversed_sorted, len(166):
Index(['2023-11-08', '2023-11-07', '2023-11-06', '2023-11-03', '2023-11-02', '2023-11-01', '2023-10-31', '2023-10-30', '2023-10-27', '2023-10-26',
       ...
       '2023-03-28', '2023-03-27', '2023-03-24', '2023-03-23', '2023-03-22', '2023-03-21', '2023-03-20', '2023-03-17', '2023-03-16', '2023-03-15'], dtype='object', length=166)

In [7]:
NYSE_dates_missing_in_df_picks  = compare_lists(dates_NYSE_reversed_sorted, l_dates_df_picks)
NYSE_dates_missing_in_df_picks.sort(reverse=True)  # sorted inplace, newest first
# save NYSE_dates_missing_in_df_picks
pickle_dump(NYSE_dates_missing_in_df_picks, path_data_dump, fp_NYSE_dates_missing_in_df_picks)   
print(f'NYSE_dates_missing_in_df_picks, (len={len(NYSE_dates_missing_in_df_picks )}):\n{NYSE_dates_missing_in_df_picks }')

NYSE_dates_missing_in_df_picks, (len=26):
['2023-10-18', '2023-10-16', '2023-10-13', '2023-10-11', '2023-10-10', '2023-10-09', '2023-10-03', '2023-09-27', '2023-09-26', '2023-09-19', '2023-09-07', '2023-09-06', '2023-08-31', '2023-08-30', '2023-08-29', '2023-08-28', '2023-08-24', '2023-08-23', '2023-08-22', '2023-08-21', '2023-08-16', '2023-07-31', '2023-07-28', '2023-07-24', '2023-07-19', '2023-07-17']

In [8]:
import pandas as pd
from yf_utils import random_slices, lookback_slices
from yf_utils import rank_perf, grp_tuples_sort_sum, top_set_sym_freq_cnt
from myUtils import pickle_load, pickle_dump

pd.set_option("display.max_rows", 20)
pd.set_option("display.max_columns", 11)
pd.set_option("display.max_colwidth", 16)
pd.set_option("display.width", 145)

path_dir = "C:/Users/ping/MyDrive/stocks/yfinance/"
path_data_dump = path_dir + "VSCode_dump/"

fp_df_close_clean = "df_close_clean"

### Set parameters ######################################################################
# fp_df_eval_results = f'df_eval_results_{run_type}'
fp_df_picks = f"df_picks"

# verbose = False  # True prints more output
verbose = True  # True prints more output

store_results = True
# store_results = False

n_samples = 1  # only need 1 sample to get the current picks

# for training, the number of days to lookback from iloc max-lookback iloc_end_train
l_days_lookbacks = [[30, 60, 120], [15, 30, 60, 120]]

l_sorted_days_lookbacks = []
for days_lookbacks in l_days_lookbacks:
    l_sorted_days_lookbacks.append(sorted(days_lookbacks))

# number of days from iloc_end_train are used to evaluate effectiveness of the training
days_eval = 0

# number of the most-common symbols from days_lookbacks' performance rankings to keep
n_top_syms = 20

# slice starts and ends for selecting the best performing symbols
syms_start = 0
syms_end = 10




# get picks of previous days by dropping the last n rows from df_current
#  drop_last_n_rows = 1 drops the last row from df_current
drop_last_n_rows = 0
drop_last_n_rows = 4



#########################################################################

print(f"verbose : {verbose }")
print(f"store_results: {store_results}")
print(f"n_samples: {n_samples}")
print(f"days_lookbacks: {days_lookbacks}")
print(f"days_eval: {days_eval}")
print(f"n_top_syms: {n_top_syms}")
print(f"syms_start: {syms_start}")
print(f"syms_end: {syms_end}")
print(f"fp_df_picks: {fp_df_picks}\n\n")

df_picks = pickle_load(path_data_dump, fp_df_picks)
df_close_clean = pickle_load(path_data_dump, fp_df_close_clean)
df_current = df_close_clean.copy()

for i, days_lookbacks in enumerate(l_sorted_days_lookbacks):

    print(f'\n\n{"%"*40:<42}{i+1} of {len(l_sorted_days_lookbacks)} days_lookbacks{"%"*40:>42}\n')
    max_days_lookbacks = max(days_lookbacks)
    print(f"max_days_lookbacks: {max_days_lookbacks}\n")

    slice_start = -(max_days_lookbacks + drop_last_n_rows)
    slice_end = -drop_last_n_rows
    if drop_last_n_rows == 0:  # return df with all rows
        df = df_current[slice_start:].copy()
    else:  # return df with dropped drop_last_n_rows rows
        df = df_current[slice_start:slice_end].copy()


    print(f"df.head():\n{df.head()}\n")        
    print(f"dropped last {drop_last_n_rows} row(s) from df")
    print(f"df.tail():\n{df.tail()}\n")
    len_df = len(df)
    # len_df_current = len(df_current)
    print(f"len(df): {len(df)}")

verbose : True
store_results: True
n_samples: 1
days_lookbacks: [15, 30, 60, 120]
days_eval: 0
n_top_syms: 20
syms_start: 0
syms_end: 10
fp_df_picks: df_picks




%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%  1 of 2 days_lookbacks  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

max_days_lookbacks: 120

df.head():
                     A         AA    AAL         AAP        AAPL  ...       ZION        ZTO         ZTS       ZUMZ        ZWS
Date                                                              ...
2023-05-15  127.489014  36.724174  14.28  120.926422  171.837967  ...  23.635796  29.160000  183.008392  16.209999  21.389919
2023-05-16  125.795670  35.840565  14.20  116.355110  171.837967  ...  23.082058  28.500000  180.619370  15.940000  21.230812
2023-05-17  127.269875  36.475971  14.91  121.075165  172.457123  ...  25.869699  28.480000  178.120865  16.840000  21.897072
2023-05-18  128.634521  36.545467  15.05  120.460373  174.813934  ...  26.927422  29.040001  178.897293  17.389999  22.774950
2023-05-19  128.365555  35.840565  14.82  116.424538  174.923798  ...  26.462816  28.750000  178.728073  16.270000  22.375916

[5 rows x 1277 columns]

dropped last 4 row(s) from df
df.tail():
                     A         AA    AAL        AAP        AAPL  ...       ZION        ZTO         ZTS       ZUMZ        ZWS
Date                                                             ...
2023-10-27  102.769997  23.410000  10.92  49.900002  168.220001  ...  29.450001  23.549999  155.657318  16.000000  25.780001
2023-10-30  101.169998  25.320000  11.18  51.330002  170.289993  ...  29.980000  23.740000  156.625000  16.309999  26.059999
2023-10-31  103.370003  25.639999  11.15  52.029999  170.770004  ...  30.850000  23.570000  157.000000  16.430000  26.459999
2023-11-01  102.860001  25.030001  11.14  51.549999  173.970001  ...  31.020000  23.500000  151.440002  16.059999  27.350000
2023-11-02  104.470001  26.070000  11.40  52.939999  177.570007  ...  33.230000  23.930000  160.910004  16.590000  28.129999

[5 rows x 1277 columns]

len(df): 120


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%  2 of 2 days_lookbacks  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

max_days_lookbacks: 120

df.head():
                     A         AA    AAL         AAP        AAPL  ...       ZION        ZTO         ZTS       ZUMZ        ZWS
Date                                                              ...
2023-05-15  127.489014  36.724174  14.28  120.926422  171.837967  ...  23.635796  29.160000  183.008392  16.209999  21.389919
2023-05-16  125.795670  35.840565  14.20  116.355110  171.837967  ...  23.082058  28.500000  180.619370  15.940000  21.230812
2023-05-17  127.269875  36.475971  14.91  121.075165  172.457123  ...  25.869699  28.480000  178.120865  16.840000  21.897072
2023-05-18  128.634521  36.545467  15.05  120.460373  174.813934  ...  26.927422  29.040001  178.897293  17.389999  22.774950
2023-05-19  128.365555  35.840565  14.82  116.424538  174.923798  ...  26.462816  28.750000  178.728073  16.270000  22.375916

[5 rows x 1277 columns]

dropped last 4 row(s) from df
df.tail():
                     A         AA    AAL        AAP        AAPL  ...       ZION        ZTO         ZTS       ZUMZ        ZWS
Date                                                             ...
2023-10-27  102.769997  23.410000  10.92  49.900002  168.220001  ...  29.450001  23.549999  155.657318  16.000000  25.780001
2023-10-30  101.169998  25.320000  11.18  51.330002  170.289993  ...  29.980000  23.740000  156.625000  16.309999  26.059999
2023-10-31  103.370003  25.639999  11.15  52.029999  170.770004  ...  30.850000  23.570000  157.000000  16.430000  26.459999
2023-11-01  102.860001  25.030001  11.14  51.549999  173.970001  ...  31.020000  23.500000  151.440002  16.059999  27.350000
2023-11-02  104.470001  26.070000  11.40  52.939999  177.570007  ...  33.230000  23.930000  160.910004  16.590000  28.129999

[5 rows x 1277 columns]

len(df): 120

In [9]:
print(f'df_current.head():\n{df_current.head()}')
print(f'df_current.tail():\n{df_current.tail()}')

df_current.head():
                    A         AA        AAL        AAP       AAPL  ...       ZION        ZTO        ZTS       ZUMZ        ZWS
Date                                                               ...
2017-11-22  65.633377  41.737015  47.427250  82.460930  41.415661  ...  38.969166  15.877837  68.290558  18.600000  23.360292
2017-11-24  66.273560  41.316128  47.329788  82.102081  41.418030  ...  38.969166  15.373776  68.501968  19.049999  23.098690
2017-11-27  66.225777  41.149719  47.193333  82.690956  41.209709  ...  39.028011  15.121749  68.742203  19.200001  23.156828
2017-11-28  67.448799  42.383041  47.973072  85.423698  40.968269  ...  40.432083  14.935061  68.598045  20.100000  23.525003
2017-11-29  65.633377  40.366657  48.002312  91.965736  40.118454  ...  41.609146  14.851050  68.809456  20.850000  23.835056

[5 rows x 1277 columns]
df_current.tail():
                     A         AA    AAL        AAP        AAPL  ...       ZION        ZTO         ZTS       ZUMZ        ZWS
Date                                                             ...
2023-11-02  104.470001  26.070000  11.40  52.939999  177.570007  ...  33.230000  23.930000  160.910004  16.590000  28.129999
2023-11-03  109.019997  26.530001  11.98  57.139999  176.649994  ...  34.759998  24.570000  162.229996  16.910000  28.650000
2023-11-06  107.529999  25.969999  11.66  56.660000  179.229996  ...  34.180000  24.420000  163.169998  16.520000  28.450001
2023-11-07  110.540001  25.540001  11.75  58.380001  181.820007  ...  34.099998  24.080000  167.160004  16.459999  28.299999
2023-11-08  109.389999  25.530001  12.01  57.639999  182.889999  ...  33.759998  24.049999  170.869995  15.910000  28.299999

[5 rows x 1277 columns]

In [10]:
print(NYSE_dates_missing_in_df_picks)

['2023-10-18', '2023-10-16', '2023-10-13', '2023-10-11', '2023-10-10', '2023-10-09', '2023-10-03', '2023-09-27', '2023-09-26', '2023-09-19', '2023-09-07', '2023-09-06', '2023-08-31', '2023-08-30', '2023-08-29', '2023-08-28', '2023-08-24', '2023-08-23', '2023-08-22', '2023-08-21', '2023-08-16', '2023-07-31', '2023-07-28', '2023-07-24', '2023-07-19', '2023-07-17']

In [11]:
def drop_dates_after_input_date(df, input_date):
  """Drops dates after the input date in a Pandas DataFrame with a Date index.

  Args:
    df: A Pandas DataFrame with a Date index.
    input_date: A datetime object.

  Returns:
    A Pandas DataFrame with the dates after the input date dropped.
  """

  # Get the index of the input date in the DataFrame.
  input_date_index = df.index.get_loc(input_date)

  # Drop the rows after the input date.
  df = df.iloc[:input_date_index + 1]

  return df

In [12]:
print(NYSE_dates_missing_in_df_picks)

['2023-10-18', '2023-10-16', '2023-10-13', '2023-10-11', '2023-10-10', '2023-10-09', '2023-10-03', '2023-09-27', '2023-09-26', '2023-09-19', '2023-09-07', '2023-09-06', '2023-08-31', '2023-08-30', '2023-08-29', '2023-08-28', '2023-08-24', '2023-08-23', '2023-08-22', '2023-08-21', '2023-08-16', '2023-07-31', '2023-07-28', '2023-07-24', '2023-07-19', '2023-07-17']

In [13]:
for i, date in enumerate(NYSE_dates_missing_in_df_picks):
  NYSE_dates_missing=NYSE_dates_missing_in_df_picks[i]
  df_ = drop_dates_after_input_date(df=df_current, input_date=NYSE_dates_missing)
  print(f'i: {i}, {df_.index[-1]}')

i: 0, 2023-10-18 00:00:00
i: 1, 2023-10-16 00:00:00
i: 2, 2023-10-13 00:00:00
i: 3, 2023-10-11 00:00:00
i: 4, 2023-10-10 00:00:00
i: 5, 2023-10-09 00:00:00
i: 6, 2023-10-03 00:00:00
i: 7, 2023-09-27 00:00:00
i: 8, 2023-09-26 00:00:00
i: 9, 2023-09-19 00:00:00
i: 10, 2023-09-07 00:00:00
i: 11, 2023-09-06 00:00:00
i: 12, 2023-08-31 00:00:00
i: 13, 2023-08-30 00:00:00
i: 14, 2023-08-29 00:00:00
i: 15, 2023-08-28 00:00:00
i: 16, 2023-08-24 00:00:00
i: 17, 2023-08-23 00:00:00
i: 18, 2023-08-22 00:00:00
i: 19, 2023-08-21 00:00:00
i: 20, 2023-08-16 00:00:00
i: 21, 2023-07-31 00:00:00
i: 22, 2023-07-28 00:00:00
i: 23, 2023-07-24 00:00:00
i: 24, 2023-07-19 00:00:00
i: 25, 2023-07-17 00:00:00

In [14]:
df_ = df_current.copy()
df_.tail(20)

                     A         AA    AAL        AAP        AAPL  ...       ZION        ZTO         ZTS       ZUMZ        ZWS
Date                                                             ...
2023-10-12  108.940002  26.785580  12.06  49.970001  180.710007  ...  35.200001  24.049999  173.893646  16.500000  26.940001
2023-10-13  110.510002  26.466942  11.72  50.750000  178.850006  ...  34.570000  24.150000  173.963486  15.810000  26.530001
2023-10-16  111.500000  26.695963  11.94  53.590000  178.720001  ...  35.919998  24.010000  174.761566  16.860001  26.820000
2023-10-17  112.400002  27.651880  11.94  54.680000  177.149994  ...  36.740002  24.010000  173.843765  17.690001  27.040001
2023-10-18  108.610001  26.407198  11.36  53.240002  175.839996  ...  35.689999  23.650000  169.135040  17.150000  25.870001
2023-10-19  109.510002  24.136894  11.45  51.299999  175.460007  ...  32.240002  23.389999  167.638626  17.219999  25.780001
2023-10-20  109.230003  23.907873  11.08  51.200001  172.880005  ...  29.959999  23.610001  166.690903  17.010000  25.590000
2023-10-23  109.339996  23.310425  11.29  48.450001  173.000000  ...  30.049999  23.370001  166.102310  16.740000  25.490000
2023-10-24  105.639999  23.340298  11.21  48.250000  173.440002  ...  29.860001  23.790001  166.720825  16.740000  25.480000
2023-10-25  103.400002  23.738596  11.04  49.840000  171.100006  ...  29.629999  23.750000  163.279068  16.770000  25.389999
2023-10-26  104.309998  23.410000  11.15  51.029999  166.889999  ...  30.450001  23.520000  157.692444  16.700001  26.030001
2023-10-27  102.769997  23.410000  10.92  49.900002  168.220001  ...  29.450001  23.549999  155.657318  16.000000  25.780001
2023-10-30  101.169998  25.320000  11.18  51.330002  170.289993  ...  29.980000  23.740000  156.625000  16.309999  26.059999
2023-10-31  103.370003  25.639999  11.15  52.029999  170.770004  ...  30.850000  23.570000  157.000000  16.430000  26.459999
2023-11-01  102.860001  25.030001  11.14  51.549999  173.970001  ...  31.020000  23.500000  151.440002  16.059999  27.350000
2023-11-02  104.470001  26.070000  11.40  52.939999  177.570007  ...  33.230000  23.930000  160.910004  16.590000  28.129999
2023-11-03  109.019997  26.530001  11.98  57.139999  176.649994  ...  34.759998  24.570000  162.229996  16.910000  28.650000
2023-11-06  107.529999  25.969999  11.66  56.660000  179.229996  ...  34.180000  24.420000  163.169998  16.520000  28.450001
2023-11-07  110.540001  25.540001  11.75  58.380001  181.820007  ...  34.099998  24.080000  167.160004  16.459999  28.299999
2023-11-08  109.389999  25.530001  12.01  57.639999  182.889999  ...  33.759998  24.049999  170.869995  15.910000  28.299999

[20 rows x 1277 columns]

In [30]:
def check_date(input_date, last_row_date, dates_NYSE):
    if input_date > last_row_date:
        raise ValueError("Error: input_date should not be later than last_row_date")
    if input_date not in dates_NYSE:
        raise ValueError(f"Error: input_date is not a NYSE trading date between {dates_NYSE[0]} and {dates_NYSE[-1]}")

In [32]:
import sys

input_date = '2023-10-29'
last_row_date = df_.index[-1].strftime('%Y-%m-%d')

try:
    check_date(input_date, last_row_date, dates_NYSE)
except ValueError as e:
    print(e)
    sys.exit(1)

iloc_last_row = len(df_) - 1
iloc_input_date = df_.index.get_loc(input_date)
rows_drop = iloc_last_row - iloc_input_date
print(f'last_row_date: {last_row_date}')
print(f'iloc_last_row: {iloc_last_row}, iloc_input_date: {iloc_input_date}, rows to drop: {rows_drop}')

Error: input_date is not a NYSE trading date between 2023-03-15 and 2023-11-08

AttributeError: 'tuple' object has no attribute 'tb_frame'

### TODO integrate above code to yf_2get_picks_trash.py

## Add picks from missing dates to df_picks

In [17]:
df_model_picks_results = pickle_load(path_data_dump, 'df_model_picks_results')
print(f'df_model_picks_results, len({len(df_model_picks_results)}):\n{df_model_picks_results}\n')

df_model_picks_results, len(125):
           date    days_lookback    syms_freq          symbols    date_buy  ... sh_SPY_sell  $_SPY_sell %_SPY_chg  dif_%_chg win
4    2023-09-01    [30, 60, 120]   sym_freq_9          ['SHV']  2023-09-05  ...       [2.0]  891.039978 -0.828065   0.909835   1
5    2023-09-01    [30, 60, 120]   sym_freq_8  ['FTSM', 'ST...  2023-09-05  ...       [2.0]  891.039978 -0.828065  -0.427302   0
6    2023-08-25    [30, 60, 120]   sym_freq_9          ['SHV']  2023-08-28  ...       [2.0]  900.700012  1.714246  -1.623670   0
7    2023-08-25    [30, 60, 120]   sym_freq_8         ['STRL']  2023-08-28  ...       [2.0]  900.700012  1.714246   2.833503   1
8    2023-08-25  [15, 30, 60,...  sym_freq_12          ['SHV']  2023-08-28  ...       [2.0]  900.700012  1.714246  -1.623670   0
..          ...              ...          ...              ...         ...  ...         ...         ...       ...        ...  ..
124  2023-03-20    [30, 60, 120]   sym_freq_9  ['FTSM', 'SHV']  2023-03-21  ...       [2.0]  788.570801 -0.792154   0.931581   1
125  2023-03-17    [30, 60, 120]   sym_freq_9  ['FTSM', 'SHV']  2023-03-20  ...       [2.0]  783.429871 -0.144761   0.188289   1
126  2023-03-17    [30, 60, 120]   sym_freq_8           ['GE']  2023-03-20  ...       [2.0]  783.429871 -0.144761   2.001963   1
127  2023-03-16    [30, 60, 120]   sym_freq_9  ['FTSM', 'SHV']  2023-03-17  ...       [2.0]  781.317688  0.543603  -0.469499   0
128  2023-03-15    [30, 60, 120]   sym_freq_9  ['FTSM', 'SHV']  2023-03-16  ...       [2.0]  794.867371  1.091222  -1.060719   0

[125 rows x 18 columns]

In [18]:
df_model_picks = pickle_load(path_data_dump, 'df_model_picks')
print(f'df_model_picks, len({len(df_model_picks)}):\n{df_model_picks}')

df_model_picks, len(4):
         date  days_lookback   syms_freq          symbols    date_buy  ... sh_SPY_sell  $_SPY_sell %_SPY_chg  dif_%_chg win
0  2023-09-08  [30, 60, 120]  sym_freq_9  ['FTSM', 'SHV']        None  ...        None         NaN       NaN        NaN   0
1  2023-09-08  [30, 60, 120]  sym_freq_8  ['DELL', 'ST...        None  ...        None         NaN       NaN        NaN   0
2  2023-09-05  [30, 60, 120]  sym_freq_9          ['SHV']  2023-09-06  ...        None         NaN       NaN        NaN   0
3  2023-09-05  [30, 60, 120]  sym_freq_8         ['FTSM']  2023-09-06  ...        None         NaN       NaN        NaN   0

[4 rows x 18 columns]